version: '3'
services:
  app:
    build: .
    container_name: fullstack_app
    ports:
      - "3000:3000"  # Port du backend
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm run start:dev
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
