version: '3'

services:
  backend:
    build:
      context: ./src/infrastructure/
      dockerfile: frameworks/backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000" 
      - "8001:8001"
    depends_on:
      - postgres
      - mongodb
    environment:
      - DB_TYPE=${DB_TYPE}
      - POSTGRES_URL=${POSTGRES_URL}
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./src/infrastructure/database/mongodb:/usr/src/infrastructure/database/mongodb
      - ./src/infrastructure/database/postgres:/usr/src/infrastructure/database/postgres
      - ./src/infrastructure/database/config:/usr/infrastructure/database/config
      - ./src/infrastructure/frameworks/backend/express:/usr/src/infrastructure/frameworks/backend/express
      - ./src/infrastructure/frameworks/backend/fastify:/usr/src/infrastructure/frameworks/backend/fastify
      - ./src/domain:/usr/src/domain
      - ./src/application:/usr/src/application

  frontend:
    build:
      context: ./src/infrastructure/frameworks/frontend/react  
    container_name: frontend
    ports:
      - "3000:3000" 
    volumes:
      - ./src/infrastructure/frameworks/frontend/react:/usr/src/infrastructure/frameworks/frontend/react
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres} 
      POSTGRES_DB: ${DB_DATABASE:-user_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=${MONGO_URL:-mongodb://root:password@mongodb:27017/triumph?authSource=admin}
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - "8081:8081"

volumes:
    mongodb_data: {}
    postgres_data: {}
    

