version: '3'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"  # Le backend est accessible sur le port 8000
    depends_on:
      - postgres
      - mongo
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: user_db
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

  frontend:
    build:
      context: ./src/infrastructure/react  # Le répertoire du frontend React
    container_name: frontend
    ports:
      - "3000:3000"  # Le frontend Vite est accessible sur le port 3000
    volumes:
      - ./src/infrastructure/react:/usr/src/app
    command: npm run dev

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/db:/data/db
      - ./database/dev.archive:/Databases/dev.archive
      - ./database/production:/Databases/production

  # mongo-express:
  #   image: mongo-express
  #   container_name: mexpress
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
  #     - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/triumph?authSource=admin
  #     - ME_CONFIG_BASICAUTH_USERNAME=mexpress
  #     - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
  #   links:
  #     - mongo
  #   restart: unless-stopped
  #   ports:
  #     - "8081:8081"

volumes:
    mongodb_data_container: {}
    postgres_data: {}


